//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSplit.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XSplit.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _18_clock_five_24 {
            get {
                object obj = ResourceManager.GetObject("18_clock_five_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AboutBroadcaster_Logo {
            get {
                object obj = ResourceManager.GetObject("AboutBroadcaster_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AboutCapture_Button {
            get {
                object obj = ResourceManager.GetObject("AboutCapture_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AboutCapture_Logo {
            get {
                object obj = ResourceManager.GetObject("AboutCapture_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AboutCapture_SplitMediaLabs {
            get {
                object obj = ResourceManager.GetObject("AboutCapture_SplitMediaLabs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_add_svc {
            get {
                object obj = ResourceManager.GetObject("addin_add_svc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_add_svc_hover {
            get {
                object obj = ResourceManager.GetObject("addin_add_svc_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_add_svc_normal {
            get {
                object obj = ResourceManager.GetObject("addin_add_svc_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_add_svc_pressed {
            get {
                object obj = ResourceManager.GetObject("addin_add_svc_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_border_bottom {
            get {
                object obj = ResourceManager.GetObject("addin_border_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_border_left {
            get {
                object obj = ResourceManager.GetObject("addin_border_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_border_right {
            get {
                object obj = ResourceManager.GetObject("addin_border_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_border_top {
            get {
                object obj = ResourceManager.GetObject("addin_border_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_button_strip_bg {
            get {
                object obj = ResourceManager.GetObject("addin_button_strip_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_content_bottom {
            get {
                object obj = ResourceManager.GetObject("addin_content_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_content_left {
            get {
                object obj = ResourceManager.GetObject("addin_content_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_content_panel_border {
            get {
                object obj = ResourceManager.GetObject("addin_content_panel_border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_content_right {
            get {
                object obj = ResourceManager.GetObject("addin_content_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_content_top {
            get {
                object obj = ResourceManager.GetObject("addin_content_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_copy_to_clipboard {
            get {
                object obj = ResourceManager.GetObject("addin_copy_to_clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_preview {
            get {
                object obj = ResourceManager.GetObject("addin_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_process_btn {
            get {
                object obj = ResourceManager.GetObject("addin_process_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_save {
            get {
                object obj = ResourceManager.GetObject("addin_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_scroll_bottom_disabled {
            get {
                object obj = ResourceManager.GetObject("addin_scroll_bottom_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_scroll_bottom_hover {
            get {
                object obj = ResourceManager.GetObject("addin_scroll_bottom_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_scroll_bottom_normal {
            get {
                object obj = ResourceManager.GetObject("addin_scroll_bottom_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_scroll_bottom_pressed {
            get {
                object obj = ResourceManager.GetObject("addin_scroll_bottom_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_scroll_top_disabled {
            get {
                object obj = ResourceManager.GetObject("addin_scroll_top_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_scroll_top_hover {
            get {
                object obj = ResourceManager.GetObject("addin_scroll_top_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_scroll_top_normal {
            get {
                object obj = ResourceManager.GetObject("addin_scroll_top_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_scroll_top_pressed {
            get {
                object obj = ResourceManager.GetObject("addin_scroll_top_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_strip_bottom {
            get {
                object obj = ResourceManager.GetObject("addin_strip_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_strip_right {
            get {
                object obj = ResourceManager.GetObject("addin_strip_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_strip_top {
            get {
                object obj = ResourceManager.GetObject("addin_strip_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_svc_btn {
            get {
                object obj = ResourceManager.GetObject("addin_svc_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_svc_btn_hover {
            get {
                object obj = ResourceManager.GetObject("addin_svc_btn_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_svc_btn_normal {
            get {
                object obj = ResourceManager.GetObject("addin_svc_btn_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_svc_btn_pressed {
            get {
                object obj = ResourceManager.GetObject("addin_svc_btn_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_tool_btn {
            get {
                object obj = ResourceManager.GetObject("addin_tool_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addin_upload_toolbar_bg {
            get {
                object obj = ResourceManager.GetObject("addin_upload_toolbar_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alpha {
            get {
                object obj = ResourceManager.GetObject("alpha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap appicon {
            get {
                object obj = ResourceManager.GetObject("appicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_get {
            get {
                object obj = ResourceManager.GetObject("application_get", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_put {
            get {
                object obj = ResourceManager.GetObject("application_put", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_middle {
            get {
                object obj = ResourceManager.GetObject("b_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_form {
            get {
                object obj = ResourceManager.GetObject("background_form", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap badgeDemo {
            get {
                object obj = ResourceManager.GetObject("badgeDemo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue {
            get {
                object obj = ResourceManager.GetObject("blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue1 {
            get {
                object obj = ResourceManager.GetObject("blue1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bmd_48x48 {
            get {
                object obj = ResourceManager.GetObject("bmd-48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap border_icon {
            get {
                object obj = ResourceManager.GetObject("border_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brightness {
            get {
                object obj = ResourceManager.GetObject("brightness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_about {
            get {
                object obj = ResourceManager.GetObject("broadcaster-about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_animated_capture {
            get {
                object obj = ResourceManager.GetObject("broadcaster_animated_capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_animated_sign_in {
            get {
                object obj = ResourceManager.GetObject("broadcaster_animated_sign_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_exit {
            get {
                object obj = ResourceManager.GetObject("broadcaster-exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_help {
            get {
                object obj = ResourceManager.GetObject("broadcaster-help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_icon_upgrade_xsplit {
            get {
                object obj = ResourceManager.GetObject("broadcaster-icon-upgrade-xsplit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Broadcaster_Logo {
            get {
                object obj = ResourceManager.GetObject("Broadcaster_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Broadcaster_Logo_Avatar {
            get {
                object obj = ResourceManager.GetObject("Broadcaster_Logo_Avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_more {
            get {
                object obj = ResourceManager.GetObject("broadcaster-more", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_my_xsplit_files {
            get {
                object obj = ResourceManager.GetObject("broadcaster-my-xsplit-files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_settings {
            get {
                object obj = ResourceManager.GetObject("broadcaster-settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_sign_in {
            get {
                object obj = ResourceManager.GetObject("broadcaster-sign-in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap broadcaster_sign_out {
            get {
                object obj = ResourceManager.GetObject("broadcaster-sign-out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon broadcaster_signed_in {
            get {
                object obj = ResourceManager.GetObject("broadcaster_signed_in", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon broadcaster_signed_out {
            get {
                object obj = ResourceManager.GetObject("broadcaster_signed_out", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_annotationNormal {
            get {
                object obj = ResourceManager.GetObject("btn_annotationNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_LiveNormal {
            get {
                object obj = ResourceManager.GetObject("btn_LiveNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnMinimizedown {
            get {
                object obj = ResourceManager.GetObject("btnMinimizedown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnMinimizeOver {
            get {
                object obj = ResourceManager.GetObject("btnMinimizeOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnMinimizeUp {
            get {
                object obj = ResourceManager.GetObject("btnMinimizeUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_add_bg {
            get {
                object obj = ResourceManager.GetObject("button-add-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_add_bg_disabled {
            get {
                object obj = ResourceManager.GetObject("button-add-bg-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_default_bg {
            get {
                object obj = ResourceManager.GetObject("button-default-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_default_selected_2 {
            get {
                object obj = ResourceManager.GetObject("button-default-selected-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_disabled {
            get {
                object obj = ResourceManager.GetObject("button-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_down {
            get {
                object obj = ResourceManager.GetObject("button-down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_down_disabled {
            get {
                object obj = ResourceManager.GetObject("button-down-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_down_pressed {
            get {
                object obj = ResourceManager.GetObject("button-down-pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_down_selected {
            get {
                object obj = ResourceManager.GetObject("button-down-selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_flickr_default_bg {
            get {
                object obj = ResourceManager.GetObject("button-flickr-default-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_flickr_disabled_bg {
            get {
                object obj = ResourceManager.GetObject("button-flickr-disabled-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_flickr_selected_bg {
            get {
                object obj = ResourceManager.GetObject("button-flickr-selected-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_up {
            get {
                object obj = ResourceManager.GetObject("button-up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_up_disabled {
            get {
                object obj = ResourceManager.GetObject("button-up-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_up_pressed {
            get {
                object obj = ResourceManager.GetObject("button-up-pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_up_selected {
            get {
                object obj = ResourceManager.GetObject("button-up-selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_xsplit_default_bg {
            get {
                object obj = ResourceManager.GetObject("button-xsplit-default-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_xsplit_disabled_bg {
            get {
                object obj = ResourceManager.GetObject("button-xsplit-disabled-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_xsplit_selected_bg {
            get {
                object obj = ResourceManager.GetObject("button-xsplit-selected-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_youtube_default_bg {
            get {
                object obj = ResourceManager.GetObject("button-youtube-default-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_youtube_disabled_bg {
            get {
                object obj = ResourceManager.GetObject("button-youtube-disabled-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_youtube_selected_bg {
            get {
                object obj = ResourceManager.GetObject("button-youtube-selected-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap capture_about {
            get {
                object obj = ResourceManager.GetObject("capture-about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox {
            get {
                object obj = ResourceManager.GetObject("checkbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox2 {
            get {
                object obj = ResourceManager.GetObject("checkbox2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_button {
            get {
                object obj = ResourceManager.GetObject("close_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_pressed {
            get {
                object obj = ResourceManager.GetObject("close-pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_selected {
            get {
                object obj = ResourceManager.GetObject("close-selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cog {
            get {
                object obj = ResourceManager.GetObject("cog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap combobox {
            get {
                object obj = ResourceManager.GetObject("combobox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap command_button {
            get {
                object obj = ResourceManager.GetObject("command_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap common_xsplit_logo {
            get {
                object obj = ResourceManager.GetObject("common_xsplit_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap content_window {
            get {
                object obj = ResourceManager.GetObject("content-window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contrast {
            get {
                object obj = ResourceManager.GetObject("contrast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_disabled {
            get {
                object obj = ResourceManager.GetObject("copy-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_pressed {
            get {
                object obj = ResourceManager.GetObject("copy-pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_selected {
            get {
                object obj = ResourceManager.GetObject("copy-selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_disabled {
            get {
                object obj = ResourceManager.GetObject("delete_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frame_bottom {
            get {
                object obj = ResourceManager.GetObject("frame_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frame_left {
            get {
                object obj = ResourceManager.GetObject("frame_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frame_left_straight {
            get {
                object obj = ResourceManager.GetObject("frame_left_straight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frame_right {
            get {
                object obj = ResourceManager.GetObject("frame_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frame_right_straight {
            get {
                object obj = ResourceManager.GetObject("frame_right_straight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frame_top {
            get {
                object obj = ResourceManager.GetObject("frame_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap green {
            get {
                object obj = ResourceManager.GetObject("green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap green_light {
            get {
                object obj = ResourceManager.GetObject("green-light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap green1 {
            get {
                object obj = ResourceManager.GetObject("green1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hue {
            get {
                object obj = ResourceManager.GetObject("hue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_capture_screen {
            get {
                object obj = ResourceManager.GetObject("icon_capture_screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_capture_webcam {
            get {
                object obj = ResourceManager.GetObject("icon_capture_webcam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_exit {
            get {
                object obj = ResourceManager.GetObject("icon_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_more {
            get {
                object obj = ResourceManager.GetObject("icon_more", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_online_meeting {
            get {
                object obj = ResourceManager.GetObject("icon_online_meeting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_settings {
            get {
                object obj = ResourceManager.GetObject("icon_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_sign_in {
            get {
                object obj = ResourceManager.GetObject("icon_sign_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_sign_out {
            get {
                object obj = ResourceManager.GetObject("icon_sign_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_upgrade_xsplit {
            get {
                object obj = ResourceManager.GetObject("icon_upgrade_xsplit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_view_files {
            get {
                object obj = ResourceManager.GetObject("icon_view_files", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconOffline {
            get {
                object obj = ResourceManager.GetObject("iconOffline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inner_panel {
            get {
                object obj = ResourceManager.GetObject("inner-panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap interface_background_widened {
            get {
                object obj = ResourceManager.GetObject("interface_background_widened", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap interface_background2 {
            get {
                object obj = ResourceManager.GetObject("interface_background2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap interfacebutton_bg {
            get {
                object obj = ResourceManager.GetObject("interfacebutton-bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JustinTV {
            get {
                object obj = ResourceManager.GetObject("JustinTV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JustinTV_logo {
            get {
                object obj = ResourceManager.GetObject("JustinTV_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lnbadgePersonal {
            get {
                object obj = ResourceManager.GetObject("lnbadgePersonal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lnbadgePremium {
            get {
                object obj = ResourceManager.GetObject("lnbadgePremium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lnbadgeStudio {
            get {
                object obj = ResourceManager.GetObject("lnbadgeStudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loader2 {
            get {
                object obj = ResourceManager.GetObject("loader2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loadingbluedots {
            get {
                object obj = ResourceManager.GetObject("loadingbluedots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loadingdots {
            get {
                object obj = ResourceManager.GetObject("loadingdots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logIN_button {
            get {
                object obj = ResourceManager.GetObject("logIN_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login_button1 {
            get {
                object obj = ResourceManager.GetObject("login_button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logon_button_pic {
            get {
                object obj = ResourceManager.GetObject("logon_button_pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logout_button {
            get {
                object obj = ResourceManager.GetObject("logout_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logout_button1 {
            get {
                object obj = ResourceManager.GetObject("logout_button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logout_left {
            get {
                object obj = ResourceManager.GetObject("Logout_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lst_movedown {
            get {
                object obj = ResourceManager.GetObject("lst_movedown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lst_movedownwhitev {
            get {
                object obj = ResourceManager.GetObject("lst_movedownwhitev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lst_moveup {
            get {
                object obj = ResourceManager.GetObject("lst_moveup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail {
            get {
                object obj = ResourceManager.GetObject("mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_blank {
            get {
                object obj = ResourceManager.GetObject("mail_blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap max_button {
            get {
                object obj = ResourceManager.GetObject("max_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_item_bg {
            get {
                object obj = ResourceManager.GetObject("menu_item_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_item_bg_bottom_sep {
            get {
                object obj = ResourceManager.GetObject("menu_item_bg_bottom_sep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_item_bg_top_sep {
            get {
                object obj = ResourceManager.GetObject("menu_item_bg_top_sep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap min_button {
            get {
                object obj = ResourceManager.GetObject("min_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file is saved on your computer but not uploaded online due to internet problems. Please contact your Systems Administrator for assistance..
        /// </summary>
        internal static string msgUpload1 {
            get {
                return ResourceManager.GetString("msgUpload1", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NewUI_background {
            get {
                object obj = ResourceManager.GetObject("NewUI_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewUI_xsplit_logo {
            get {
                object obj = ResourceManager.GetObject("NewUI_xsplit_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notification_icon_info {
            get {
                object obj = ResourceManager.GetObject("notification_icon_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notification_icon_question {
            get {
                object obj = ResourceManager.GetObject("notification_icon_question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notification_icon_stop {
            get {
                object obj = ResourceManager.GetObject("notification_icon_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notification_icon_warning {
            get {
                object obj = ResourceManager.GetObject("notification_icon_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pin {
            get {
                object obj = ResourceManager.GetObject("pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pin_off {
            get {
                object obj = ResourceManager.GetObject("pin_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pin_on {
            get {
                object obj = ResourceManager.GetObject("pin-on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] pipette {
            get {
                object obj = ResourceManager.GetObject("pipette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap press_camera {
            get {
                object obj = ResourceManager.GetObject("press_camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap press_video {
            get {
                object obj = ResourceManager.GetObject("press_video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pressed_live {
            get {
                object obj = ResourceManager.GetObject("pressed_live", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pressed_live_blue {
            get {
                object obj = ResourceManager.GetObject("pressed_live_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preview {
            get {
                object obj = ResourceManager.GetObject("preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preview_disabled {
            get {
                object obj = ResourceManager.GetObject("preview-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preview_golive_down {
            get {
                object obj = ResourceManager.GetObject("preview_golive_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preview_golive_next {
            get {
                object obj = ResourceManager.GetObject("preview_golive_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preview_pressed {
            get {
                object obj = ResourceManager.GetObject("preview-pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preview_selected {
            get {
                object obj = ResourceManager.GetObject("preview-selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radiobutton {
            get {
                object obj = ResourceManager.GetObject("radiobutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radiobutton2 {
            get {
                object obj = ResourceManager.GetObject("radiobutton2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap range {
            get {
                object obj = ResourceManager.GetObject("range", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap red {
            get {
                object obj = ResourceManager.GetObject("red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap red_light {
            get {
                object obj = ResourceManager.GetObject("red-light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap red1 {
            get {
                object obj = ResourceManager.GetObject("red1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_hoverl {
            get {
                object obj = ResourceManager.GetObject("refresh_hoverl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_normal {
            get {
                object obj = ResourceManager.GetObject("refresh-normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap restore_button {
            get {
                object obj = ResourceManager.GetObject("restore_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saturation {
            get {
                object obj = ResourceManager.GetObject("saturation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_disabled {
            get {
                object obj = ResourceManager.GetObject("save-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_pressed {
            get {
                object obj = ResourceManager.GetObject("save-pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_selected {
            get {
                object obj = ResourceManager.GetObject("save-selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings_background {
            get {
                object obj = ResourceManager.GetObject("settings_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap small_close {
            get {
                object obj = ResourceManager.GetObject("small_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap small_close_click {
            get {
                object obj = ResourceManager.GetObject("small_close_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap small_close_hover {
            get {
                object obj = ResourceManager.GetObject("small_close_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap speaker_off {
            get {
                object obj = ResourceManager.GetObject("speaker_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap speaker_on {
            get {
                object obj = ResourceManager.GetObject("speaker_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stepback {
            get {
                object obj = ResourceManager.GetObject("stepback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stepforward {
            get {
                object obj = ResourceManager.GetObject("stepforward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab {
            get {
                object obj = ResourceManager.GetObject("tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap temp_language_area {
            get {
                object obj = ResourceManager.GetObject("temp_language_area", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap title_bar {
            get {
                object obj = ResourceManager.GetObject("title_bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tray_animated_capture {
            get {
                object obj = ResourceManager.GetObject("tray_animated_capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tray_animated_sign_in {
            get {
                object obj = ResourceManager.GetObject("tray_animated_sign_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon tray_icon_active {
            get {
                object obj = ResourceManager.GetObject("tray_icon_active", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tray_icon_inactive {
            get {
                object obj = ResourceManager.GetObject("tray_icon_inactive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tray_signed_in {
            get {
                object obj = ResourceManager.GetObject("tray_signed_in", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tray_signed_out {
            get {
                object obj = ResourceManager.GetObject("tray_signed_out", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unpin {
            get {
                object obj = ResourceManager.GetObject("unpin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upload_disabled {
            get {
                object obj = ResourceManager.GetObject("upload-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upload_notext {
            get {
                object obj = ResourceManager.GetObject("upload-notext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upload_pressed {
            get {
                object obj = ResourceManager.GetObject("upload-pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upload_progress {
            get {
                object obj = ResourceManager.GetObject("upload_progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upload_selected_notext {
            get {
                object obj = ResourceManager.GetObject("upload-selected-notext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_btn_2 {
            get {
                object obj = ResourceManager.GetObject("user_btn_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_btn_2_click {
            get {
                object obj = ResourceManager.GetObject("user_btn_2_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_btn_2_hover {
            get {
                object obj = ResourceManager.GetObject("user_btn_2_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_btn_bg {
            get {
                object obj = ResourceManager.GetObject("user_btn_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_btn_click {
            get {
                object obj = ResourceManager.GetObject("user_btn_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_btn_hover {
            get {
                object obj = ResourceManager.GetObject("user_btn_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UStream {
            get {
                object obj = ResourceManager.GetObject("UStream", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ustream_48 {
            get {
                object obj = ResourceManager.GetObject("ustream-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon xsplit_common_icon {
            get {
                object obj = ResourceManager.GetObject("xsplit_common_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xsplit_logo {
            get {
                object obj = ResourceManager.GetObject("xsplit_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xsplit_logo_2 {
            get {
                object obj = ResourceManager.GetObject("xsplit_logo_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS &quot;Addin&quot;;
        ///CREATE TABLE &quot;Addin&quot; (&quot;Id&quot; integer PRIMARY KEY  NOT NULL ,&quot;User_Id&quot; integer NOT NULL ,&quot;Type&quot; integer NOT NULL ,&quot;Name&quot; varchar(50) NOT NULL , &quot;Settings&quot; BLOB);
        ///DROP TABLE IF EXISTS &quot;AddinType&quot;;
        ///CREATE TABLE &quot;AddinType&quot; (
        ///    [ID] integer PRIMARY KEY AUTOINCREMENT NOT NULL,
        ///    [Name] varchar(50) NOT NULL,
        ///    [ExpandedIcon] image,
        ///    [CollapsedIcon] image
        ///);
        ///INSERT INTO &quot;AddinType&quot; VALUES(0,&apos;XSplitOffLine&apos;,X&apos;0000010003003030000001002000A8250000360000002020000001002000A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xsplit_sql {
            get {
                return ResourceManager.GetString("xsplit.sql", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon XSplitBroadcaster {
            get {
                object obj = ResourceManager.GetObject("XSplitBroadcaster", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSplit Broadcaster.
        /// </summary>
        internal static string XSplitBroadcasterTitleText {
            get {
                return ResourceManager.GetString("XSplitBroadcasterTitleText", resourceCulture);
            }
        }
        
        internal static byte[] XSplitUtils {
            get {
                object obj = ResourceManager.GetObject("XSplitUtils", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yellow_light {
            get {
                object obj = ResourceManager.GetObject("yellow-light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap youtube_logo {
            get {
                object obj = ResourceManager.GetObject("youtube_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
